{{- range $i, $value := $.Values.pools -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: {{ template "name" $ }}-{{ $value.name }}-block
    label:
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
      rook_cluster: {{ template "name" $ }}
    {{- if $value.storageClass.enabled }}
    {{- if $value.storageClass.default }}
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    {{ end -}}
    {{ end }}
provisioner: rook.io/block
parameters:
  pool: {{ $value.name }}
  clusterName: {{ template "name" $ }}
  clusterNamespace: {{ $.Release.Namespace }}
{{ end -}}
